---
title: "Rcpp Functions"
description: >
  Rcpp functions are functions written in C++ and are made available in R by the package Rcpp.
  The package RcppArmadillo is also needed to run some tensor operations
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rcpp-functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(PanelPRO)
```

We have incorporated functions written in C++ to reduce the computational runtime of the peeling-paring algorithm in the `PanelPRO` package. It is well known that R is not the fastest programming language and has a large overhead for function calls. In `PanelPRO`, a recursive implementation of peeling and paring forms the backbone for computing carrier probabilities. The runtime of this algorithm (Fernando et al., 1993) scales exponentially with the number of genes in model, so it is important to keep this runtime low as the number of genes increases.

This vignette describes how we have re-written some of the time-consuming functions in C++, giving a clinically significant reduction in runtime.


## Required packages

The interface between C++ and R is provided by the R package `Rcpp`. Compared to a regular R package, there are a few differences to ensure that the C++ code is made available to other functions in the package. We refer to <https://adv-r.hadley.nz/rcpp.html> and in particular <https://adv-r.hadley.nz/rcpp.html#rcpp-package> for more details. Essentially, this boils down to adding the following to the `DESCRIPTION` file:

```
LinkingTo: Rcpp, RcppArmadillo  
Imports: Rcpp (>= 1.0.3)  
```

The RcppArmadillo package is another R/C++ interface that provides a linear algebra toolkit (see <http://arma.sourceforge.net/> and <https://cran.r-project.org/web/packages/RcppArmadillo/index.html>).

Some additional software may be required to compile C++. Windows requires `RTools` and Mac OS requires `Xcode Developer Tools`. Linux should have a built-in C++ compiler.

## Where to put the C++ code

The C++ code lives in the folder `PanelPRO\src`, where header files (`.h`) declare and document functions and implementation files (`.cpp`) contain the function definitions.

## Building the package

Once any necessary software for compiling C++ has been installed and the appropriate header/implementation files have been placed in `PanelPRO\src` the `PanelPRO` package can be built. For example, in RStudio, the __Clean and Rebuild__ function calls `Rcpp::compileAttributes()`, which compiles the C++ code and packages the remaining R code.
  
<br />

## Overview of functions written in C++

The bulk of the runtime gain comes from the C++ implementation of the peeling and paring algorithm. We have also re-written functions that rely on `for` loops, which are notoriously slow in R. Note that in C++, indexing starts at 0, whereas in R it starts at 1.

### Inheritance probability calculation

This has been renamed `calInheritanceProb` and is a straightforward 'translation' of the corresponding R code, now deprecated.

### Genotype prevalence calculation

This has been renamed `calPrevalences` and is a straightforward 'translation' of the corresponding R code, now deprecated.

### Peeling and paring algorithm

The helper functions for this algorithm are in `peelingParingHelper.cpp` and the main function call is in `peelingParing.cpp`. `idx` indicates the corresponding row number in the pedigree data frame, and not the `ID` identifiers in the pedigree. This results in fewer look-ups needed each time an individual in the pedigree is accessed. 

The paper Fernando et al. 1993 should be read in conjunction with the implementation of the peeling algorithm. Equation numbers referring to the paper have been quoted in comments throughout the function code to ease interpretability.

There has been a conscious decision to sacrifice some readability in favor of performance by vectorizing functions instead of writing loops, and also by making __in place__ function calls. Therefore, the algorithm alters underlying pieces of memory by reference and avoids copying. This is essential for ensuring adequate performance. In particular, `mat.each_col` or `mat.each_row` or `cube.each_slice` are key operations.

The implementation intentionally mimics the now-deprecated R implementation, but with more readability. The `sweep` function was used extensively in the R implementation; while useful this hid recycling of margins (also known as 'broadcasting') and data types.

## Calling C++ within R

Once the package has been compiled, the C++ functions are made available to R within the package. R objects (such as matrices and data frames) can be passed to C++ and one can then execute these functions. For example: 

```
posterior_probs <- peelingParing(probandIndexes, idMatrix, E, C, 
                                 prev, LIK, TR, antProb, postProb)
```
where `peelingParing` is a C++ function and the arguments are R objects.
  
<br />

## References 

Fernando, R. L., C. Stricker, and R. C. Elston. "An efficient algorithm to compute the posterior genotypic distribution for every member of a pedigree without loops." Theoretical and Applied Genetics 87.1 (1993): 89-93.

