# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inheritance probability from genotypes
#' 
#' Returns the inheritance probability tensor given the matrix of possible genotypes
#' 
#' @details
#' The base cube `M` defined in the body of `calInheritanceProb` is used to 
#' calculate the inheritance probabilities for each possible genotype. 
#' 
#' The first dimension corresponds to the father, the second dimension to the 
#' mother, and the third dimension to the child, such that `M` should be 
#' indexed as `M(father_index, mother_index, child_index)`. 
#' 
#' Along each dimension, the first index (`0`) corresponds to 
#' wildtype/noncarrier, i.e. neither allele has the mutation at this locus; 
#' the second index (`1`) corresponds to heterozygous carrier, i.e. one of 
#' the alleles is mutated and the other is not; and the third index (`2`) 
#' corresponds to homozygous carrier, i.e. both alleles carry the mutation. 
#' 
#' Each element corresponds to the probability that the child has the 
#' genotype represented by the third dimension, given that their parents have 
#' the genotypes represented by the first and second dimensions. 
#' 
#' Examples: 
#' 
#' `M(1, 0, 2) == 0`: Father is heterozygous carrier, mother is wildtype, and 
#' child is homozygous carrier. This is an impossible configuration, since 
#' there is no way for the child to inherit a mutated allele from their 
#' mother, so the probability is `0`. 
#' 
#' `M(0, 1, 0) == 0.5`: Father is wildtype, mother is heterozygous carrier, 
#' and child is wildtype. The child always inherits a wildtype allele from 
#' their father and has a 50/50 chance of inheriting a wildtype allele from 
#' their mother, so there is a `0.5` probability of being wildtype. 
#' 
#' `M(0, 2, 1) == 1`: Father is wildtype, mother is homozygous carrier, and 
#' child is heterozygous carrier. The child always inherits a wildtype 
#' allele from their father and always inherits a mutated allele from their 
#' mother, so the child must be heterozygous, hence a probability of `1`. 
#' 
#' @param possGenotypes matrix called possGenotypes
#' @return 3D Tensor (cube) giving the transition/inheritance probabilities
.calInheritanceProb <- function(possGenotypes) {
    .Call(`_PanelPRO_calInheritanceProb`, possGenotypes)
}

#' Compute prevalences for each admissible Genotype
#' 
#' Returns the inheritance probability tensor given the matrix of possible genotypes
#'
#' @param margPrevs the marginal prevalence matrix of each mutation in each pedigree member
#' @param possGenotypes matrix called possGenotypes
#' @return Matrix giving the prevalences for each pedigree member
.calPrevalences <- function(margPrevs, possGenotypes) {
    .Call(`_PanelPRO_calPrevalences`, margPrevs, possGenotypes)
}

#' Calculate Anterior Probability
#' 
#' Calculates the anterior probability of idx
#' 
#' We assume that we have already checked for loops and that there are no loops
#' 
#' @param idx The idx number of the proband (C++ row number)
#' @param idMatrix The matrix representing the idx numbers of the ID, MotherID and FatherID
#' @param mates The `matrix' specifying the mates
#' @param children The `cube' specifying the children
#' @param prevalence The `matrix' specifying the prevalences
#' @param likelihood The `matrix' specifying the likelihoods (penetrances)
#' @param transition The `cube' specifying the transition probabilities from mother and father to child
#' @param antProb A placeholder to memoise the recursive function output of calAntProb, size #Members x #Genotypes
#' @param postProb A placeholder to memoise the recursive function output of calPostProb, size #Members x #Members x #Genotypes
#' @return Values of the anterior probability of idx having possible genotypes
.calAntProb <- function(idx, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb) {
    .Call(`_PanelPRO_calAntProb`, idx, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb)
}

#' Calculate Posterior Probability
#' 
#' Calculates the posterior probability of idx and mateIdx
#' 
#' We assume that we have already checked for loops and that there are no loops
#' @param idx The idx number of the proband (C++ row number)
#' @param mateIdx The idx number of the mate of `idx' (C++ row number)
#' @param idMatrix The matrix representing the idx numbers of the ID, MotherID and FatherID
#' @param mates The `matrix' specifying the mates
#' @param children The `cube' specifying the children
#' @param prevalence The `matrix' specifying the prevalences
#' @param likelihood The `matrix' specifying the likelihoods (penetrances)
#' @param transition The `cube' specifying the transition probabilities from mother and father to child
#' @param antProb A placeholder to memoise the recursive function output of calAntProb, size #Members x #Genotypes
#' @param postProb A placeholder to memoise the recursive function output of calPostProb, size #Members x #Members x #Genotypes
#' @return Values of the posterior probability of idx and mateIdx having possible genotypes
.calPostProb <- function(idx, mateIdx, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb) {
    .Call(`_PanelPRO_calPostProb`, idx, mateIdx, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb)
}

#' Peeling and Paring
#' 
#' Calculates the posterior probabilities of genotypes of probands given inputs
#' 
#' Calls calAntProb and calPostProb recursively
#' NB: Require that NAs in antProb and postProb are set to 0
#' @param probandIdxs The idx numbers of the probands in the ID column
#' @param idMatrix The matrix representing the idx numbers of the ID, MotherID and FatherID
#' @param mates The `matrix' specifying the mates
#' @param children The `cube' specifying the children
#' @param prevalence The `matrix' specifying the prevalences
#' @param likelihood The `matrix' specifying the likelihoods (penetrances)
#' @param transition The `cube' specifying the transition probabilities from mother and father to child
#' @param antProb A placeholder to memoise the recursive function output of calAntProb
#' @param postProb A placeholder to memoise the recursive function output of calPostProb
#' @return Matrix of the posterior probabilities of ID having certain genotypes
.peelingParing <- function(probandIdxs, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb) {
    .Call(`_PanelPRO_peelingParing`, probandIdxs, idMatrix, mates, children, prevalence, likelihood, transition, antProb, postProb)
}

#' getFatherIdx
#' 
#' Gets the index number of the Father of proband
#' 
#' Columns in idMatrix are 0, 1, 2 (ID, MotherID, FatherID)
#' @param idx The idx number of the proband in the ID column (C++ row number)
#' @param idMatrix The matrix representing the ID numbers of the ID, MotherID and FatherID
#' @return Father's index (row number)
.getFatherIdx <- function(idx, idMatrix) {
    .Call(`_PanelPRO_getFatherIdx`, idx, idMatrix)
}

#' getMotherIdx
#' 
#' Gets the index number of the mother of proband
#' 
#' Columns in idMatrix are 0, 1, 2 (ID, MotherID, FatherID)
#' @param idx The idx number of the proband in the ID column (C++ row number)
#' @param idMatrix The matrix representing the ID numbers of the ID, MotherID and FatherID
#' @return Mother's index (row number)
.getMotherIdx <- function(idx, idMatrix) {
    .Call(`_PanelPRO_getMotherIdx`, idx, idMatrix)
}

#' getSibsIdxs
#' 
#' Gets the index numbers of possible siblings of proband
#' 
#' Columns in idMatrix are 0, 1, 2 (ID, MotherID, FatherID)
#' @param idx The idx number of the proband in the ID column (C++ row number)
#' @param idMatrix The matrix representing the ID numbers of the ID, MotherID and FatherID
#' @param children The `cube' specifying the children
#' @return Indexes of siblings
.getSibsIdxs <- function(idx, idMatrix, children) {
    .Call(`_PanelPRO_getSibsIdxs`, idx, idMatrix, children)
}

#' getMatesIdxs
#' 
#' Gets the index numbers of possible mates of proband
#' @param idx The idx number of the proband (C++ row number)
#' @param mates The `matrix' specifying the mates
#' @return Idxs of mates
.getMatesIdxs <- function(idx, mates) {
    .Call(`_PanelPRO_getMatesIdxs`, idx, mates)
}

#' getOtherMatesIdxs
#'
#' Gets the index numbers of possible mates of idx who are not mateIdx
#' @param idx The idx number of the proband (C++ row number)
#' @param mateIdx The idx number of the mate of the proband
#' @param mates The `matrix' specifying the mates
#' @return Idxs of other mates
.getOtherMatesIdxs <- function(idx, mateIdx, mates) {
    .Call(`_PanelPRO_getOtherMatesIdxs`, idx, mateIdx, mates)
}

#' getChildrenIdxs
#' 
#' Gets the index numbers of possible children between idx and mateIDX
#' @param idx The idx number of the proband (C++ row number)
#' @param mateIdx The other parent
#' @param children The `cube' specifying the children
#' @return Idxs of chidlren
.getChildrenIdxs <- function(idx, mateIdx, children) {
    .Call(`_PanelPRO_getChildrenIdxs`, idx, mateIdx, children)
}

